### ISSUE TITLE
LIBUSB::ERROR_ACCESS in libusb_open

### ISSUE THREAD

**Issue by arvinwiyono** [perryn/blinky#11]
Hi Perryn,

I have done everything to make this work, but everytime I initialize Blinky, I always got this error message. Can you help me with this?

arvin@arvin-VirtualBox:~$ irb
**r2.2.0 :001 > require 'blinky'**
 => true 
**2.2.0 :002 > l = Blinky.new**
LIBUSB::ERROR_ACCESS: LIBUSB::ERROR_ACCESS in libusb_open
    from /home/arvin/.rvm/gems/ruby-2.2.0/gems/libusb-0.2.2/lib/libusb/constants.rb:46:in `raise_error'
    from /home/arvin/.rvm/gems/ruby-2.2.0/gems/libusb-0.2.2/lib/libusb/device.rb:58:in`open'
    from /home/arvin/.rvm/gems/ruby-2.2.0/gems/libusb-0.2.2/lib/libusb/compat.rb:175:in `open'
    from /home/arvin/.rvm/gems/ruby-2.2.0/gems/blinky-0.0.12/lib/blinky/light_factory.rb:11:in`block in detect_lights'
    from /home/arvin/.rvm/gems/ruby-2.2.0/gems/blinky-0.0.12/lib/blinky/light_factory.rb:7:in `each'
    from /home/arvin/.rvm/gems/ruby-2.2.0/gems/blinky-0.0.12/lib/blinky/light_factory.rb:7:in`detect_lights'
    from /home/arvin/.rvm/gems/ruby-2.2.0/gems/blinky-0.0.12/lib/blinky.rb:26:in `initialize'

**Comment by perryn** [comment]
hi

what OS are you using?

**Comment by arvinwiyono** [comment]
It is Ubuntu 14.04 with Virtual Box Windows host
