### ISSUE TITLE
Installing Gem issue

### ISSUE THREAD

**Issue by eddiejaoude** [perryn/blinky#5]
I get this error on Ubuntu 13.11 when installing the Gem....

```
eddie@ubuntu13-10:~$ sudo gem install blinky
Building native extensions.  This could take a while...
ERROR:  Error installing blinky:
    ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from extconf.rb:4:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.3 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/ffi-1.9.3/ext/ffi_c/gem_make.out
```

Any ideas?

**Comment by perryn** [comment]
apparently the standard ruby library is not sufficient to build native extensions - you need to install the dev ruby package. Something like:

sudo apt-get install ruby-dev

Ill update the doco
